extends RefCounted
class_name OriginStories
## Per the request: a class-themed origin story shown once, at the
## very start of a character's life in the Overworld — the opening
## entry in their ongoing Journal. Deliberately written with the
## setting's own established tone: grim, cynical, morbidly funny,
## crude where it earns it — corrupt officials, terrible luck, worse
## hygiene, everyone dying of something. Every piece here is original
## writing, not drawn from any published sourcebook. {name} and
## {career} are filled in per character; results read differently for
## every combination of race/career even from a fixed pool of eight.

const STORIES := {
	"Warrior": "They told {name} that soldiering builds character. What it actually built was a permanent stoop, a cough that never quite goes away, and a deep, personal hatred of the word \"volunteers.\" The sergeant who signed {name} up as a {career} was three parts gin and one part promises he had no intention of keeping, and by the time the hangover wore off there was already a halberd in hand and a captain screaming something about the Empire's eternal glory over the sound of someone else being sick into a ditch. Glory, it turns out, smells like unwashed wool and looks a lot like standing in the rain for six hours waiting for a fight that might not even happen. Still — steady pay, someone else's problem to stab, and a truly spectacular collection of scars to lie about later. Could be worse. Could be dead. Give it time.",
	"Ranger": "The trees don't care that {name} used to have a proper bed, or a roof, or neighbours who weren't actively trying to eat each other. Out here, as a {career}, it's just {name}, a bow with more personality than most people, and the growing suspicion that every rustle in the undergrowth is something with too many teeth and an appetite. The old hermit who taught the trade had a habit of eating things no sane person should, and a laugh like a man who'd made peace with dying alone and violently — which, given the neighbourhood, was probably just being realistic. Fresh air, they said. Character-building solitude, they said. Nobody mentioned the part where you go three weeks without a bath and start finding that oddly comforting, or the specific horror of realizing the thing following you for the last mile has been doing so on purpose.",
	"Rogue": "Nobody teaches you the trade so much as you survive learning it, usually by way of a slap round the head and someone shouting \"not like THAT, you absolute waste of a pocket.\" {name} came up as a {career} the honest way — which is to say, dishonestly, badly, and with a truly heroic number of near-misses involving the Watch, several enraged shopkeepers, and one memorably furious woman with a rolling pin who could run faster than anyone had a right to expect. The guild takes a cut, the law takes an interest, and the streets take whatever's left when both of those go wrong at once. Still, there's an art to it — a genuine, honest-to-Ranald art to convincing someone their coin purse simply walked off on its own — and {name}'s getting good enough at it that the near-misses are starting to feel like they might, eventually, stop.",
	"Academic": "Somewhere in a draughty library that smelled permanently of mildew and other people's bad decisions, {name} discovered that knowledge is a truly excellent way to become poor, unpopular, and mildly cursed, sometimes all in the same afternoon. Training as a {career} meant years of a professor who'd clearly lost several arguments with the subject matter and at least one actual finger, muttering about margins of texts nobody with any self-preservation instinct should be reading aloud. The pay is terrible, the hours worse, and there's a very specific kind of dread that comes with realizing the book you've been quoting at parties to sound clever has a footnote in someone else's handwriting reading \"do not.\" Still — {name} can read four dead languages, correctly identify at least half of what's crawling around in the sewers by smell alone, and has never once, not once, been the most cursed person in the room. That's practically a resume.",
	"Burgher": "The guild hall reeks of tallow candles, spilled ale, and the specific, curdled ambition of men who'd sell their own mothers for a better trade route. {name} learned the family business the way everyone does — badly, expensively, and under the watchful, disapproving eye of a relative who never once let anyone forget exactly how much this was costing them. Becoming a proper {career} means understanding contracts, tariffs, and the fine art of smiling at a man while quietly calculating how much it would cost to have him quietly disappear. Success smells like fresh bread and new coin; failure smells like the debtor's block. {name}'s made peace with knowing which one is more likely on any given Konistag, and has gotten very, very good at looking confident anyway.",
	"Courtier": "Nobody actually likes anyone at court — that would be terribly gauche — but {name} learned early that liking people was never really the point. Rising as a {career} meant mastering the noble art of smiling warmly at someone while privately composing the letter that ends their career, learning which fork is for which course and which lord is sleeping with which other lord's wife, and developing a truly world-class poker face for the moment someone's wine turns out to have been meant for someone else entirely. The clothes are gorgeous, the food is extraordinary, and the whole gilded, perfumed circus is one bad rumour away from a duel, a scandal, or a very convenient \"accident.\" {name} has learned to always, always taste the wine first.",
	"Peasant": "Nobody writes songs about mud. They should — {name} has seen enough of it to know it deserves one, ideally a long, miserable dirge about the specific way it gets into absolutely everything you own. Growing up a {career} meant work before dawn, taxes that somehow went up even in years the harvest didn't, and a village priest whose sermons on divine mercy got noticeably shorter every time the plague cart came through. There's an honesty to it that the fancy folk in the towns wouldn't understand — you work, you eat (usually), you bury somebody (regularly), and you get on with it, because the alternative is lying down in a field and letting the crows have first pick. {name} left with a strong back, a stronger stomach, and absolutely no illusions left about how the world actually works.",
	"Riverfolk": "The river gives you fish, trade, and a truly reliable chance of drowning, sometimes all in the same afternoon. {name} grew up as a {career} learning to read the current the way other people read faces — which stretches hide sandbars, which eddies hide something worse, and exactly how far you can push a smuggling run before the river wardens stop pretending not to notice. Barge life means bad weather, worse company, and a captain who swears the river spirits take offense if you whistle after dark, which nobody's brave enough to actually test. Still — there's good coin in cargo nobody asks too many questions about, and {name}'s learned to swim, lie, and haggle, roughly in that order of how often each one's actually saved a life.",
}

## Returns the origin story text for the given career, with {name} and
## {career} filled in — falls back to the Warrior story (the most
## setting-generic of the eight) if a class name isn't recognised,
## rather than showing nothing at all.
static func get_story(character_name: String, career_class: String, career_name: String) -> String:
	var template: String = STORIES.get(career_class, STORIES["Warrior"])
	return template.replace("{name}", character_name).replace("{career}", career_name)
